# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 977b0bae545831de8de365eaaeff68dd30613617d0ab134d0d656b3ca373762e7beeee59d2fd151125ded48e488587e40a815f5e199227c8a2007d1d72b44801

test:
  secret_key_base: 52f75427dca188bb95b0eec732acd013166e2c1478c8ecc20abaa18f2472ba86815196d4dd5ca537320ee2c4fa40217d8286cc54c896a8fe054fa424a5cf42bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
